### ISSUE TITLE
Plugin failure: tag-wrangler TypeError: c is not a constructor

### ISSUE THREAD

**Issue by pindab0ter** [pjeby/tag-wrangler#137]
When trying to load the plugin, this error appears in the console:

```
Plugin failure: tag-wrangler TypeError: c is not a constructor
    at e.<anonymous> (app.js:1:2292587)
    at app.js:1:237138
    at Object.next (app.js:1:237243)
    at a (app.js:1:235961)
```

Tag wrangler version 0.6.1
Obsidian 1.6.5

Linter community plugin is installed, but not enabled.

In the Obsidian Sandbox, it works without a problem, even with the Linter plugin installed and enabled.

**Comment by pindab0ter** [comment]
Removing and installing the extension fixed it for me.
